### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pedropazello** [pedropazello/first_fm_api#1]
# API endpoints and features:
## Playlists:
- [ ] User playlists
   - [ ] List playlists
   - [ ] Create playlists
   - [ ] Delete playlists
   - [ ] Show playlists
   - [ ] Update playlists
- [ ] Public playlists
  - [ ] List public playlists

## Songs:

All songs are public. The User can add favorite songs.

- [ ] Songs
  - [ ] Add songs
  - [ ] List songs
  - [ ] Show songs

- [ ] Favorite songs
   - [ ] Add a favorite song
   - [ ] Delete favorite songs
   - [ ] List favorite songs

## Bands:

All bands are public. The User can add favorite bands.

- [ ] Bands
  - [ ] Add bands
  - [ ] List bands
  - [ ] Show band

- [ ] Favorite bands
   - [ ] Add a favorite band
   - [ ] Delete favorite bands
   - [ ] List favorite bands

## Genres:

TODO
